sudo: false
dist: trusty

#language: cpp
script: make test
env:
  global:
    - CXX='g++-6'
    - LDFLAGS='-Lgoogletest-release-1.8.0/googlemock/gtest'
  matrix:
    - CPPFLAGS='-std=c++14 -Igoogletest-release-1.8.0/googletest/include'
    - CPPFLAGS='-std=c++14 -Igoogletest-release-1.8.0/googletest/include -DWATCHED'

# https://stackoverflow.com/questions/45276457/how-to-use-latest-boost-version-in-travis-ci
addons:
  apt:
    sources:
    - sourceline: 'ppa:mhier/libboost-latest'
    - ubuntu-toolchain-r-test
    packages:
    - g++-6
    - boost1.67
  
# Dependencies
before_install:
  - wget https://github.com/google/googletest/archive/release-1.8.0.tar.gz
  - tar -xf release-1.8.0.tar.gz
  - pushd googletest-release-1.8.0
  - cmake .
  - make
  - popd
