sudo: false
dist: trusty

language: cpp
script: make test
env:
  - CPPFLAGS='-std=c++14 -Igoogletest-release-1.8.0/googletest/include'
  - CPPFLAGS='-std=c++14 -Igoogletest-release-1.8.0/googletest/include -DWATCHED'
  - LDFLAGS='-Lgoogletest-release-1.8.0/googlemock/gtest'

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-6
    - libboost1.60-dev
  
# Dependencies
before_install:
  - wget https://github.com/google/googletest/archive/release-1.8.0.tar.gz
  - tar -xf release-1.8.0.tar.gz
  - pushd googletest-release-1.8.0
  - cmake .
  - make
  - popd
