# Need gcc-4.8
sudo: required
dist: xenial

language: cpp
script: make test
env:
  - CPPFLAGS='-std=c++14'
  - CPPFLAGS='-std=c++14 -DWATCHED'

# Dependencies
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libboost-dev
  - wget https://github.com/google/googletest/archive/release-1.8.0.tar.gz
  - tar -xf release-1.8.0.tar.gz
  - pushd googletest-release-1.8.0
  - cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr
  - make
  - sudo make install
  - popd
